e_courier/driver/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name="driver"
urlpatterns = [
      path('', views.Active_driver, name='Active_driver'),
      path('driver/', views.driver, name='driver'),
      path('driver_form/', views.driver_form,name='driver_form'),
      path('edit/<id>/', views.edit,name='edit'),
      path('update/<id>/', views.update,name='update'),

      path('driver_login/', auth_views.LoginView.as_view(template_name='account/driver_login.html'), name='driver_login'),#driver
      path('logout/', auth_views.LogoutView.as_view(), name='logout'),
      
      path('DriverSignUp/', views.DriverSignUp, name='DriverSignUp'),#driver
      
      path('driver_profile_page/', views.driver_profile_page, name='driver_profile_page'),#driver
      path('driver_see_the_request/', views.driver_see_the_request.as_view(template_name='tasks.html'), name='driver_see_the_request'),

      # path('DeliveryUpdate/<int:id>/',views.DeliveryUpdate.as_view(),name="DeliveryUpdate" ),
      path('driver_see_delivery_details/',views.driver_see_delivery_details,name="driver_see_delivery_details" ),
      # path('ForShareLocation/',views.ForShareLocation,name="ForShareLocation"),
      path('livelocationshare/<int:id>/',views.livelocationshare,name="livelocationshare"),
      path('locationUpdate/<int:order_id>/',views.locationUpdate,name="locationUpdate"),
      path('ViewMapLocation/<int:id>/',views.ViewMapLocation,name="ViewMapLocation"),
]

e_courier/e_courier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account import views as user_views
from .import views

from django.contrib.staticfiles.templatetags.staticfiles import static as staticfiles
from django.utils.translation import ugettext_lazy as _
from material.admin.sites import site

admin.site.site_header = ('Sample Delivery')
admin.site.site_title = ('Sample Delivery')
admin.site.index_title = ('Sample Delivery')


urlpatterns = [
    # path('admin/', include('material.admin.urls')),
    path('admin/', admin.site.urls),
    path('profile/',user_views.profile, name='profile'),
    path('home',views.HomePage,name='home'),
    path('AboutPage/',views.AboutPage.as_view(),name='AboutPage'),
    path('account/', include('account.urls',namespace="account")),
    path('account/', include('django.contrib.auth.urls')),
    path('delivery_service/', include('delivery_service.urls')),
    path('Factory/', include('factoryHead.urls')),
    # path('notification/', include('notification.urls')),
    path('', include('driver.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThankstPage.as_view(), name='thanks'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_courier/factoryHead/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name='FactoryHead'
urlpatterns = [
    path('FactoryList/',views.FactoryList.as_view(),name='FactoryList'),
    path('FactoryEmployeeList/<int:pk>/',views.FactoryEmployeeList.as_view(), name='FactoryEmployeeList'),
    path('FactoryDetails/<int:pk>/',views.FactoryDetails.as_view(), name='FactoryDetails'),
    path('totalpayment/', views.totalpayment, name='totalpayment'),
    path('FactoryInvoicePrint/<int:pk>/', views.FactoryInvoicePrint.as_view(), name='FactoryInvoicePrint'),
    ]

e_courier/factoryHead/models.py
from django.db import models

# Create your models here.

e_courier/factoryHead/views.py
from django.http import request
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView

import industry
from account.models import Profile
from delivery_service.models import DelevaryInfo
from industry.models import IndustryName, PriceSet, Industry
from django.db.models import Sum, Count, OuterRef, Subquery


class FactoryList(ListView):
    context_object_name = 'Factorys'
    model = IndustryName
    template_name = 'factorylist.html'


class FactoryEmployeeList(DetailView):
    context_object_name = 'FactoryDetalis'
    model = IndustryName
    template_name = 'factoryDetails.html'



class FactoryInvoicePrint(DetailView):
    context_object_name = 'Factoryinvoice'
    model = Profile
    model2 = DelevaryInfo
    template_name = 'invoice.html'



class FactoryDetails(DetailView):
    context_object_name = 'FactoryDetalis'
    model = Profile
    # print(Profile.objects.get(id=id).industrys)
    # x = DelevaryInfo.objects.filter(industry=OuterRef("industry")).order_by("-client")
    # y = DelevaryInfo.objects.all().annotate(z=Subquery(x.values('client_id')))
    # print("y = ",y)
    template_name = 'employeeBillDetails.html'

    def total_bill(self, profile):
        employee = profile.FactoryInvoice.all()
        total = 0
        for e in employee:
            if str(e.order.order_status) == '0':
                total += e.industry.price
        return total

    def get_context_data(self, **kwargs):
        context = super(FactoryDetails, self).get_context_data(**kwargs)
        print(kwargs)
        context['total_bill'] = self.total_bill(kwargs['object'])

        return context

def totalpayment(request):
    total = Profile.objects.all()
    order = []
    groups = DelevaryInfo.objects.select_related('Bill').values('industry')
    print(groups)
    result = DelevaryInfo.objects.values('industry').order_by('client').annotate(total_price=Sum('industry'))
    # print(result)
    x = DelevaryInfo.objects.raw('SELECT *,sum(price) from industry')
    from django.db import connection
    print("c = ", connection.queries)
    print("total = ", x.query)
    # for item in groups:
    #     print(item)
    # for delivery_info in total:
        # print(delivery_info.user)
        # print("factory name = ",delivery_info.factoryName.name)
        # if str(delivery_info.user) in str(delivery_info.factoryName.name):
        #     print("x", delivery_info.user)
    return render(request,'accounts/totalBill.html',)

e_courier/factoryHead/templates/employeeBillDetails.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block body %}
                <section>
                    <div class="section-header">
						<ol class="breadcrumb">
							<li class="active">Invoice</li>
						</ol>
					</div>
					<div class="section-body">
                        <div class="row">
							<div class="col-lg-12">
								<div class="card card-printable style-default-light">
									<div class="card-head">
										<div class="tools">
											<div class="btn-group">
												<a class="btn btn-floating-action btn-primary" href="javascript:void(0);" onclick="javascript:window.print();"><i class="md md-print"></i></a>
											</div>
										</div>
									</div><!--end .card-head -->
									<div class="card-body style-default-bright" id="print">
		<!-- BEGIN INVOICE DESCRIPTION -->
										<div class="row">
											<div class="col-xs-8">
												<h4 class="text-light">Delivery Details</h4>

											</div><!--end .col -->
											<div class="col-xs-4">
												<div class="well">

													<div class="clearfix">
														<div class="pull-left"> TOTAL INVOICE : </div>
														<div class="pull-right"> ${{ total_bill }} </div>
													</div>

												</div>
											</div><!--end .col -->
										</div><!--end .row -->
										<!-- END INVOICE DESCRIPTION -->
										<!-- BEGIN INVOICE HEADER -->
										<div class="row">
											<!--<div class="col-xs-2">
												<img src="{% static 'img/django_logo.png' %}" class="invoice_logo" width="100%">
											</div>-->
											<div class="col-xs-8">
												<h1 class="text-light" style="margin-top: 0px; color: #f70b0b">Sample <strong class="text-accent-dark" style="color: #1ab394">Delivery</strong></h1>
												<p> <br></p>
											</div>
											<div class="col-xs-4 text-right">
												<h1 class="text-light text-default-light">Invoice</h1>
											</div>
										</div><!--end .row -->
										<!-- END INVOICE HEADER -->

										<br/>





                                        <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>From to Destination</th>
                        <th>Bill</th>
                        <th>Date</th>
                    </tr>
                </thead>
                <tbody>

 {% for employee in FactoryDetalis.FactoryInvoice.all %}
 {% if employee.order.order_status == '0' %}
        <tr class="gradeX">
            <td><b>{{employee.order.from_location}}</b> to <b>{{employee.order.to_location}}</b> and product type <b>{{employee.order.product_type}}</b></td>
         <td class="prc">{{employee.industry.price}}</td>
         <td class="prc">{{employee.order.Date}}</td>
<!--         <td class="prc">{{ total_bill }}</td>-->


</tr>


{% endif %}
{% endfor %}
<!-- <td class="prc"> Total Bill : {{ total_bill }}</td>-->
</tr>
</tbody>
  </table>


										<br/>

										<!-- BEGIN INVOICE PRODUCTS -->
										<div class="row">
											<div class="col-md-12">
												<table class="table">
													<thead>
														<tr>
															<th style="width:60px" class="text-center">QTY</th>
															<th class="text-left">DESCRIPTION</th>
                                                            <th style="width:90px" class="text-right">RATE</th>
															<th style="width:90px" class="text-right">AMOUNT</th>
														</tr>
													</thead>
													<tbody>

														<tr>
															<td colspan="2" rowspan="4">
																<h3 class="text-light opacity-50">Invoice notes</h3>
																<p><small>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</small></p><br><br>
																<p><strong><em>Recevied By __________________</em></strong></p>
															</td>
                                                      <td class="text-right"><strong>Subtotal</strong></td>

														</tr>
														<tr>
															<td class="text-right hidden-border"><strong>TAKA</strong></td>
															<td class="text-right hidden-border">${{ total_bill }}</td>
														</tr>

														</tr>

													</tbody>
												</table>
											</div><!--end .col -->
										</div><!--end .row -->
										<!-- END INVOICE PRODUCTS -->

									</div><!--end .card-body -->
								</div><!--end .card -->
							</div><!--end .col -->
						</div><!--end .row -->
					</div><!--end .section-body -->
                </section>

{% endblock %}

e_courier/factoryHead/templates/factoryDetails.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block body %}

<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap Table with Add and Delete Row Feature</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style type="text/css">
    body {
        color: #000000;
        background: #000000;
		font-family: 'Open Sans', sans-serif;
	}
	.table-wrapper {
		width: 700px;
		margin: 30px auto;
        background: #fff;
        padding: 20px;
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
    }
    .table-title {
        padding-bottom: 10px;
        margin: 0 0 10px;
    }
    .table-title h2 {
        margin: 6px 0 0;
        font-size: 22px;
    }
    .table-title .add-new {
        float: right;
		height: 30px;
		font-weight: bold;
		font-size: 12px;
		text-shadow: none;
		min-width: 100px;
		border-radius: 50px;
		line-height: 13px;
    }
	.table-title .add-new i {
		margin-right: 4px;
	}
    table.table {
        table-layout: fixed;
    }
    table.table tr th, table.table tr td {
        border-color: #e9e9e9;
    }
    table.table th i {
        font-size: 13px;
        margin: 0 5px;
        cursor: pointer;
    }
    table.table th:last-child {
        width: 100px;
    }
    table.table td a {
		cursor: pointer;
        display: inline-block;
        margin: 0 5px;
		min-width: 24px;
    }
	table.table td a.add {
        color: #27C46B;
    }
    table.table td a.edit {
        color: #FFC107;
    }
    table.table td a.delete {
        color: #E34724;
    }
    table.table td i {
        font-size: 19px;
    }
	table.table td a.add i {
        font-size: 24px;
    	margin-right: -1px;
        position: relative;
        top: 3px;
    }
    table.table .form-control {
        height: 32px;
        line-height: 32px;
        box-shadow: none;
        border-radius: 2px;
    }
	table.table .form-control.error {
		border-color: #f50000;
	}
	table.table td .add {
		display: none;
	}
</style>

</head>
<body>

<p style="font-size:30px; color:red;text-align:center;">All Employee List For {{FactoryDetalis.name}}</p><hr>
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">

                    <div class="col-sm-8"><h2>Employee <b>List</b></h2></div>
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Employee Name</th>
                        <th>View Details</th>
                    </tr>
                </thead>
                <tbody>

{% for employee in FactoryDetalis.FactoryName.all %}
        <tr class="gradeX">
            <td><li> {{employee.user}}</li></td>

         <td>
<!--     <a href="{% url 'FactoryHead:FactoryDetails' employee.id%}" class="btn btn-primary btnclick"><i class="glyphicon glyphicon-ok"></i></a>-->

     <a href="{% url 'FactoryHead:FactoryDetails' employee.id%}" class="btn ink-reaction btn-floating-action btn-primary"><i class="md md-print"></i></a></li></h3>

         </td>
</tr>

{% endfor %}
</tr>
</tbody>
  </table>
        </div>
    </div>
</body>
</html>

{% endblock %}

e_courier/factoryHead/templates/factorylist.html
{% extends "layout.html" %}
{% load bootstrap3 %}
{% block body %}


 <section>
					<div class="section-body">
						<div class="row">

							<!-- BEGIN  - FORM -->
							<div class="col-lg-12">
								<div class="card">
									<div class="card-head style-primary">
										<header>All Factory List</header>
										<div class="tools">
											<a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
											<a class="btn
											btn-icon-toggle btn-close"><i class="md md-close"></i></a>
										</div>
									</div>
									<div class="card-body">
<ol>
{% for factory in Factorys%}

	<h3><li><a href="{% url 'FactoryHead:FactoryEmployeeList' factory.id %}">{{factory.name}}</a></li></h3>
<!--    <a href="{% url 'FactoryHead:FactoryInvoicePrint' factory.id %}" class="btn ink-reaction btn-floating-action btn-primary"><i class="md md-print"></i></a></li></h3>-->

{% endfor%}
    </ol>

										</div><!--end .card-body -->
										</div><!--end .card -->



							</div><!--end .col -->
							<!-- END FORM - TIME ON SITE -->

						</div><!--end .row -->
					</div><!--end .section-body -->
				</section>


{% endblock %}

e_courier/factoryHead/templates/invoice.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block body %}

<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap Table with Add and Delete Row Feature</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<style type="text/css">
    body {
        color: #000000;
        background: #000000;
		font-family: 'Open Sans', sans-serif;
	}
	.table-wrapper {
		width: 700px;
		margin: 30px auto;
        background: #fff;
        padding: 20px;
        box-shadow: 0 1px 1px rgba(0,0,0,.05);
    }
    .table-title {
        padding-bottom: 10px;
        margin: 0 0 10px;
    }
    .table-title h2 {
        margin: 6px 0 0;
        font-size: 22px;
    }
    .table-title .add-new {
        float: right;
		height: 30px;
		font-weight: bold;
		font-size: 12px;
		text-shadow: none;
		min-width: 100px;
		border-radius: 50px;
		line-height: 13px;
    }
	.table-title .add-new i {
		margin-right: 4px;
	}
    table.table {
        table-layout: fixed;
    }
    table.table tr th, table.table tr td {
        border-color: #e9e9e9;
    }
    table.table th i {
        font-size: 13px;
        margin: 0 5px;
        cursor: pointer;
    }
    table.table th:last-child {
        width: 100px;
    }
    table.table td a {
		cursor: pointer;
        display: inline-block;
        margin: 0 5px;
		min-width: 24px;
    }
	table.table td a.add {
        color: #27C46B;
    }
    table.table td a.edit {
        color: #FFC107;
    }
    table.table td a.delete {
        color: #E34724;
    }
    table.table td i {
        font-size: 19px;
    }
	table.table td a.add i {
        font-size: 24px;
    	margin-right: -1px;
        position: relative;
        top: 3px;
    }
    table.table .form-control {
        height: 32px;
        line-height: 32px;
        box-shadow: none;
        border-radius: 2px;
    }
	table.table .form-control.error {
		border-color: #f50000;
	}
	table.table td .add {
		display: none;
	}
</style>

</head>
<body>

<p style="font-size:30px; color:red;text-align:center;">All Employee List For {{Factoryinvoice.client.FactoryName}}</p><hr>
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">

                    <div class="col-sm-8"><h2>Bill <b>List</b></h2></div>
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Delivery List</th>
                        <th>Bill</th>
                    </tr>
                </thead>
                <tbody>

<!--	{% for source in Factoryinvoice.FactoryInvoice.all %}-->
<!--   <table>-->
<!--      <tr>-->
<!--          <td>{{ source }}</td>-->
<!--          <td>-->
<!--              {% if factoryName == source.client.factoryName %}-->
<!--                Just now!.............-->
<!--              {% endif %}-->
<!--          </td>-->
<!--      </tr>-->
<!--   </table>-->
<!--{% endfor %}-->

<!--	{% for source in Factoryinvoice.FactoryInvoice.all %}-->
<!--        <tr class="gradeX">-->
<!--			<td><b>{{source.client.factoryName}}</b> : <b>{{employee.order.from_location}}</b> to <b>{{employee.order.to_location}}</b> and product type <b>{{employee.order.product_type}}</b></td>-->
<!--         <td class="prc">{{employee.industry.price}}</td>-->


<!--</tr>-->


<!--{% endfor %}-->




{% for employee in Factoryinvoice.FactoryInvoice.all %}
{% ifequal employee employee.client.factoryName %}
        Just now!
      {% endifequal %}
        <tr class="gradeX">
			<td><b>{{employee.client.user}}</b> : <b>{{employee.order.from_location}}</b> to <b>{{employee.order.to_location}}</b> and product type <b>{{employee.order.product_type}}</b></td>
         <td class="prc">{{employee.industry.price}}</td>


</tr>


{% endfor %}





</tr>
</tbody>
  </table>
        </div>
    </div>
</body>
</html>


            {% for order in order %}
                <section>
                    <div class="section-header">
						<ol class="breadcrumb">
							<li class="active">Invoice</li>
						</ol>
					</div>
					<div class="section-body">
                        <div class="row">
							<div class="col-lg-12">
								<div class="card card-printable style-default-light">
									<div class="card-head">
										<div class="tools">
											<div class="btn-group">
												<a class="btn btn-floating-action btn-primary" href="javascript:void(0);" onclick="javascript:window.print();"><i class="md md-print"></i></a>
											</div>
										</div>
									</div><!--end .card-head -->
									<div class="card-body style-default-bright" id="print">

										<!-- BEGIN INVOICE HEADER -->
										<div class="row">

											<div class="col-xs-8">
												<h1 class="text-light" style="margin-top: 0px; color: #f70b0b">E-courier <strong class="text-accent-dark" style="color: #1ab394">Service</strong></h1>
												<p> address<br>Dhaka</p>
											</div>
											<div class="col-xs-4 text-right">
												<h1 class="text-light text-default-light">Invoice</h1>
											</div>
										</div><!--end .row -->
										<!-- END INVOICE HEADER -->

										<br/>

										<!-- BEGIN INVOICE DESCRIPTION -->
										<div class="row">
											<div class="col-xs-8">
												<h4 class="text-light">Delivery Details</h4>
												<address>
													<strong>From Location: {{ order.from_location }}</strong><br>
													<strong>To Location: {{ order.to_location }}</strong><br>
													<b>Product Type:</b> {{ order.product_type }}
													<br>
													<b>Phone Number: </b>{{ order.phone }}

													<br>
													<b>Payment: </b>{{ order.payment_option }}
													</strong>
												</address>
											</div><!--end .col -->
											<div class="col-xs-4">
												<div class="well">
													<div class="clearfix">
														<div class="pull-left"> INVOICE NO : </div>
														<div class="pull-right"> {{ order.id }} </div>
													</div>
													<div class="clearfix">
														<div class="pull-left"> INVOICE DATE : </div>
														<div class="pull-right"> $0.00 </div>
													</div>
													<div class="clearfix">
														<div class="pull-left"> DELEVERY DATE : </div>
														<div class="pull-right"> {{ order.Date }} </div>
													</div>
												</div>
											</div><!--end .col -->
										</div><!--end .row -->
										<!-- END INVOICE DESCRIPTION -->

										<br/>

										<!-- BEGIN INVOICE PRODUCTS -->
										<div class="row">
											<div class="col-md-12">
												<table class="table">
													<thead>
														<tr>
															<th style="width:60px" class="text-center">QTY</th>
															<th class="text-left">DESCRIPTION</th>
                                                            <th style="width:90px" class="text-right">RATE</th>
															<th style="width:90px" class="text-right">AMOUNT</th>
														</tr>
													</thead>
													<tbody>

														<tr>
															<td colspan="2" rowspan="4">
																<h3 class="text-light opacity-50">Invoice notes</h3>
																<p><small>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</small></p><br><br>
																<p><strong><em>Recevied By __________________</em></strong></p>
															</td>
															<td class="text-right"><strong>Subtotal</strong></td>

														</tr>
														<tr>
															<td class="text-right hidden-border"><strong>TAKA</strong></td>
															<td class="text-right hidden-border">$0.00</td>
														</tr>

													</tbody>
												</table>
											</div><!--end .col -->
										</div><!--end .row -->
										<!-- END INVOICE PRODUCTS -->

									</div><!--end .card-body -->
								</div><!--end .card -->
							</div><!--end .col -->
						</div><!--end .row -->
					</div><!--end .section-body -->
                </section>
            {% endfor %}

{% endblock %}