e_courier/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name='accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp, name='signup'),

    # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('help/', views.help.as_view(), name='help'),
    path('SearchResultsView/', views.SearchResultsView, name='SearchResultsView'),
    path('totalBill/', views.totalBill, name='totalBill'),
    path('customer_service/', views.customer_service.as_view(), name='customer_service'),
    path('all_delivery_for_show_user/', views.all_delivery_for_show_user, name='all_delivery_for_show_user'),
    path('client_see_driver_details/', views.client_see_driver_details, name="client_see_driver_details"),
    path('charge/<int:delivery_id>/', views.charge, name="charge"),
    path('rating_enter/<int:order_id>/', views.rating_enter, name="rating_enter"),
]

e_courier/delivery_service/urls.py
from django.urls import path
from .import views
from .views import(
   delivery_request,
   wait_sms
)
app_name='delivery_service'
urlpatterns = [
      path('', views.delivery_request, name='delivery_request'),
      # path('sms_send/', views.sms_send, name='sms_send'),
      path('wait_sms/',views.wait_sms,name='wait_sms'),
      path('all_delivery/',views.all_delivery,name='all_delivery'),
      path('tracker/',views.tracker,name='tracker'),
      path('all_latest_delivery_order/',views.all_latest_delivery_order,name='all_latest_delivery_order'),
      path('show/<order_id>/',views.show,name='show'),
      # path('edit_delivery/<int:order_id>/',views.edit_delivery,name="edit_delivery" ),
      path('edit_delivery/<order_id>/', views.edit_delivery,name='edit_delivery'),
      # path('update_delivery/<order_id>/', views.update_delivery,name='update_delivery'),
      path('DeliveryDetail/<int:id>/',views.DeliveryDetail,name="DeliveryDetail" ),
      path('delivery_destroy/<order_id>/',views.delivery_destroy,name="delivery_destroy" ),
      path('cancel_ride/',views.cancel_ride,name="cancel_ride" ),

      path('see/<int:my_id>/', views.see, name='see'),
      path('send/', views.send, name='send'),

      path('delivery_track_update/', views.delivery_track_update, name='delivery_track_update'),
      path('delivery_track_add/', views.delivery_track_add, name='delivery_track_add'),
      path('ClientChart/', views.ClientChart.as_view(), name='ClientChart'),
      path('GazipurZone/', views.GazipurZone, name='GazipurZone'),
      path('BonaniZone/', views.BonaniZone, name='BonaniZone'),
      path('click_for_send_driver_details/<int:my_id>/', views.click_for_send_driver_details, name='click_for_send_driver_details'),
      path('client_see_driver_details/<int:request_id>/', views.client_see_driver_details, name='client_see_driver_details'),
      path('driver_choose_present_location/',views.driver_choose_present_location,name="driver_choose_present_location"),
   ]

e_courier/driver/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name="driver"
urlpatterns = [
      path('', views.Active_driver, name='Active_driver'),
      path('driver/', views.driver, name='driver'),
      path('driver_form/', views.driver_form,name='driver_form'),
      path('edit/<id>/', views.edit,name='edit'),
      path('update/<id>/', views.update,name='update'),

      path('driver_login/', auth_views.LoginView.as_view(template_name='account/driver_login.html'), name='driver_login'),#driver
      path('logout/', auth_views.LogoutView.as_view(), name='logout'),
      
      path('DriverSignUp/', views.DriverSignUp, name='DriverSignUp'),#driver
      
      path('driver_profile_page/', views.driver_profile_page, name='driver_profile_page'),#driver
      path('driver_see_the_request/', views.driver_see_the_request.as_view(template_name='tasks.html'), name='driver_see_the_request'),

      # path('DeliveryUpdate/<int:id>/',views.DeliveryUpdate.as_view(),name="DeliveryUpdate" ),
      path('driver_see_delivery_details/',views.driver_see_delivery_details,name="driver_see_delivery_details" ),
      # path('ForShareLocation/',views.ForShareLocation,name="ForShareLocation"),
      path('livelocationshare/<int:id>/',views.livelocationshare,name="livelocationshare"),
      path('locationUpdate/<int:order_id>/',views.locationUpdate,name="locationUpdate"),
      path('ViewMapLocation/<int:id>/',views.ViewMapLocation,name="ViewMapLocation"),
]

e_courier/e_courier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account import views as user_views
from .import views

from django.contrib.staticfiles.templatetags.staticfiles import static as staticfiles
from django.utils.translation import ugettext_lazy as _
from material.admin.sites import site

admin.site.site_header = ('Sample Delivery')
admin.site.site_title = ('Sample Delivery')
admin.site.index_title = ('Sample Delivery')


urlpatterns = [
    # path('admin/', include('material.admin.urls')),
    path('admin/', admin.site.urls),
    path('profile/',user_views.profile, name='profile'),
    path('home',views.HomePage,name='home'),
    path('AboutPage/',views.AboutPage.as_view(),name='AboutPage'),
    path('account/', include('account.urls',namespace="account")),
    path('account/', include('django.contrib.auth.urls')),
    path('delivery_service/', include('delivery_service.urls')),
    path('Factory/', include('factoryHead.urls')),
    # path('notification/', include('notification.urls')),
    path('', include('driver.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThankstPage.as_view(), name='thanks'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_courier/delivery_service/forms.py
from django import forms

## -- from models -- ##
from industry.models import Industry
from .models import DeliveryProduct, TypesOfProduct, DelevaryInfo, OrderUpdate


## ----
## -- for product delivery Form -- ##
class deliverForm(forms.ModelForm):
    class Meta:
        model = DeliveryProduct
        fields = ['from_location', 'to_location', 'PresentAddress','product_type', 'phone', 'weight']
        labels = {
            'from_location': 'From industry : ',
            'to_location': 'To industry : ',
            'PresentAddress': 'Present Address',
            'product_type': 'Product Type : ',
            'weight': 'Weight : ',
            'image': 'Product Picture :',
            'phone': 'phone',
        }


class deliverFormEdit(forms.ModelForm):
    class Meta:
        model = DeliveryProduct
        fields = ['from_location', 'to_location','Date','order_status', 'product_type', 'phone', 'weight']
        labels = {
            'from_location': 'From Location : ',
            'to_location': 'To Location : ',
            'product_type': 'Product Type : ',
            'weight': 'Weight : ',
            'image': 'Product Picture :',
            'Date': 'Date',
            'order_status': 'order status',
            'phone': 'phone',
        }


class DelevaryInfoForm(forms.ModelForm):
    class Meta:
        model = DelevaryInfo
        fields = ['rating']




class OrderUpdateForm(forms.ModelForm):
    class Meta:
        model = OrderUpdate
        fields = ['update_id', 'order_id', 'update_desc', 'timestamp']
        labels = {
            'update_id': 'Update ID : ',
            'order_id': 'Order ID : ',
            'update_desc': 'Update Description',
            'timestamp': 'Time : ',
        }

class OrderUpdateLocationForm(forms.ModelForm):
    class Meta:
        model = OrderUpdate
        fields = ['update_id', 'order_id', 'update_desc', 'timestamp']
        labels = {
            'update_id': 'Update ID : ',
            'order_id': 'Order ID : ',
            'update_desc': 'Update Description',
            'timestamp': 'Time : ',
        }

e_courier/delivery_service/views.py
from django.shortcuts import render,redirect
from django.shortcuts import get_object_or_404
import json
from account.models import Profile
from delivery_service.models import DelevaryInfo, OrderUpdate
from industry.models import Location
from .forms import deliverForm, deliverFormEdit, OrderUpdateForm
from driver.models import DriverProfile
from .models import DeliveryProduct,TypesOfProduct
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse
from django.views.generic import DetailView
from django.db.models import ProtectedError
from django.views.generic import ListView, TemplateView

# Create your views here.
@login_required
def all_delivery(request):
    orders = DeliveryProduct.objects.all().order_by('-Date').filter(order_status='1')
    return render(request, 'index_delivery_details.html', {'orders': orders})

@login_required
def all_latest_delivery_order(request):
    orders = DelevaryInfo.objects.all()
    return render(request, 'all_latest_delivery_order.html', {'orders': orders})

@login_required
def delivery_track_update(request):
    track = OrderUpdate.objects.all().order_by('-order_id')
    return render(request,'system_admin_track_update.html',{'track':track})

@login_required
def delivery_track_add(request):
    if request.method == 'POST':
        add = OrderUpdateForm(request.POST, request.FILES)
        if add.is_valid():
            add_info = add.save()
            new_add_info = OrderUpdateForm()
        else:
            note = "failed.Try again!!"
        return render(request, 'add_track_update.html', {'new_add_info': new_add_info})
    else:
        add = OrderUpdateForm()
        return render(request, 'add_track_update.html', {'new_add_info': add})

# def track_id_separate(request,order_id):
#     track_id = OrderUpdate.objects.filter(id=order_id)
#     return render(request,)

@login_required
def show(request, order_id):
    order = DelevaryInfo.objects.filter(id=order_id)
    return render(request, 'show_delivery.html', {'order': order})


def delivery_request(request):
    if request.method == 'POST':
        form_delivery=deliverForm(request.POST,request.FILES)
        if form_delivery.is_valid():
            delivery_product_info = form_delivery.save()
            update = OrderUpdate(order_id=delivery_product_info.id, update_desc="The order has been placed")
            update.save()
            id = delivery_product_info.id
            client = Profile.objects.get(user=request.user)
            DelevaryInfo(client=client, order=delivery_product_info).save()
            note = "Thanks for your request!! Wait a few minutes!! Car is on the way!!"
            new_form_delivery=deliverForm()
        else:
            note="failed.Try again!!"
        return render(request,'delivery_form.html',{'deliveryform': new_form_delivery,'note': note,'id': id})
    else:
        form_delivery = deliverForm()
        return render(request,'delivery_form.html', {'deliveryform':form_delivery})


@login_required
def edit_delivery(request, order_id):
    order = DeliveryProduct.objects.get(id=order_id)
    if request.POST:
        form = deliverFormEdit(request.POST, instance=order)
        if form.is_valid():
            if form.save():
                return redirect(reverse('delivery_service:edit_delivery', args=(order.id,)), messages.success(request, 'Order was successfully updated.', 'alert-success'))
            else:
                return redirect(reverse('delivery_service:edit_delivery', args=(order.id,)), messages.error(request, 'Data is not saved', 'alert-danger'))
        else:
            print(form.errors)
            return redirect(reverse('delivery_service:edit_delivery', args=(order.id,)), messages.error(request, 'Form is not valid', 'alert-danger'))
    else:
        form = deliverFormEdit(instance=order)
        return render(request, 'edit_delivery.html', {'form': form})

@login_required
def delivery_destroy(request, order_id):
    order = DeliveryProduct.objects.get(id=order_id)
    try:
        order.delete()
    except ProtectedError:
        error_message = "This object can't be deleted!!"
        return JsonResponse(error_message)
    # order.delete()
    return redirect(reverse('delivery_service:all_delivery'), messages.success(request, 'Order was successfully deleted.', 'alert-success'))




def DeliveryDetail(request, id=None):
    obj = get_object_or_404(DeliveryProduct, id=id)
    
    context= {'obj': obj,
              }
    
    return render(request, 'delivery_detail_view.html', context)

def wait_sms(request):

    return render(request,'wait.html')

@login_required
def driver_choose_present_location(request):
    return render(request,'driver_choose_present_location.html')
def see(request,my_id):
    obj = get_object_or_404(DeliveryProduct, id=my_id)
    context = {
        'object': obj
    }
    return render(request, "delivery_view_for_driver_send.html", context)


@login_required
def send(request):
    delivery_info_list = DelevaryInfo.objects.filter(driver=None)
    order = []
    for delivery_info in delivery_info_list:
        order += [delivery_info.order]

    return render(request, 'driver_see.html', {'order': order})


@login_required
def GazipurZone(request):
    delivery_info_list = DelevaryInfo.objects.filter(driver=None)
    order = []
    for delivery_info in delivery_info_list:
        order += [delivery_info.order]

    return render(request, 'for_gajipur_zone.html', {'order': order})

@login_required
def BonaniZone(request):
    delivery_info_list = DelevaryInfo.objects.filter(driver=None)
    order = []
    for delivery_info in delivery_info_list:
        order += [delivery_info.order]

    return render(request, 'for_Bonani_zone.html', {'order': order})


@login_required
def click_for_send_driver_details(request,my_id):
    x= get_object_or_404(DelevaryInfo,id=my_id)
    model = get_object_or_404(DeliveryProduct,id=my_id)

    object = DriverProfile.objects.get(user=request.user)

    delivery_details = DelevaryInfo.objects.get(order=model)
    delivery_details.driver = object
    delivery_details.save()
    obj = DriverProfile.objects.get(user__username=request.user.username)
    context = {
        'obj': obj,
        'model': model,
        'x':x
    }
    # print(driver)
    return render(request, 'click_for_send_driver_details.html', context)



def cancel_ride(request):
    order = DelevaryInfo.objects.all()
    for delivery_info in order:
        print(delivery_info.driver)

    # try:
    #     order.delete()
    # except ProtectedError:
    #     error_message = "This object can't be deleted!!"
    #     return JsonResponse(error_message)
    # # order.delete()
    return render(request,'click_for_send_driver_details.html')

def client_see_driver_details(request, request_id,**kwargs):
    model = get_object_or_404(DriverProfile, id=request_id)
    if model.id:
        driver = DriverProfile.objects.filter(user=request.user)

    else:
        driver = None
    context = {
        'request': model,
        'driver': driver,
    }
    return render(request, 'accounts/client_see_driver_details.html', context)

# def tracker(request):
#     if request.method=="POST":
#         orderId = request.POST.get('orderId', '')
#         phone = request.POST.get('phone', '')
#         try:
#             order = DeliveryProduct.objects.filter(id=orderId, phone=phone)
#             if len(order)>0:
#                 update = OrderUpdate.objects.filter(order_id=orderId)
#                 updates = []
#                 for item in update:
#                     updates.append({'text': item.update_desc, 'time': item.timestamp})
#                     response = json.dumps(updates, default=str)
#                 return HttpResponse(response)
#             else:
#                 return HttpResponse('{}')
#         except Exception as e:
#             return HttpResponse('{}')
#
#     return render(request, 'tracker.html')



def tracker(request):
    if request.method=="POST":
        orderId = request.POST.get('orderId', '')
        # phone = request.POST.get('phone', '')
        try:
            # order = DeliveryProduct.objects.filter(id=orderId, phone=phone)
            order = DeliveryProduct.objects.filter(id=orderId)
            if len(order)>0:
                update = OrderUpdate.objects.filter(order_id=orderId)
                updates = []
                # value1=[]
                # value2=[]
                for item in update:
                    updates.append({'text': item.longitude,'number': item.latitude,'time': item.timestamp})
                    response = json.dumps(updates, default=str)
                    # x = item.longitude
                    # y=item.latitude
                    # # print(" x = ",x,"y = ",y)
                    # value1.append(x)
                    # value2.append(y)
                return HttpResponse(response)
            else:
                return HttpResponse('{}')
        except Exception as e:
            return HttpResponse('{}')

    return render(request, 'tracker.html')

class ClientChart(TemplateView):
    template_name = 'ClientChart.html'

e_courier/delivery_service/templates/add_track_update.html
{% extends 'layout.html' %}
{% load bootstrap3 %}
{% block body %}

<div class="container">
<h1>Add Track </h1>
<form action="{% url 'delivery_service:delivery_track_add' %}"method="post"enctype="multipart/form-data">
	{% csrf_token %}
     {% bootstrap_form new_add_info %}
   <input type="submit"class="btn btn-default" value="Send Request">
</form>
</div>
{% endblock %}

e_courier/delivery_service/templates/all_latest_delivery_order.html
{% extends 'layout.html' %}

{% block body %}
<section>
<div class="section-body">
       <!-- BEGIN DATATABLE 2 -->
  <div class="row">
      <div class="col-lg-12">
            <div class="card">
               <div class="card-head style-primary">
                  <header>All Orders Data</header>
                      <div class="tools">
                          <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
                               <a class="btn btn-icon-toggle btn-close"><i class="md md-close"></i></a>
                                    </div>
                              </div>
                              <div class="card-body">
                                  <div class="table-responsive">
                                   <table id="datatable2" class="table order-column hover">
                                       <thead>
                                          <tr>
                                             <th>ID</th>
<!--                                             <th>User ID</th>-->
                                              <th>from_location</th>
                                               <th>to_location</th>
                                              <th>product_type</th>
                                               <th>Date</th>
<!--                                                 <th>Bill</th>-->
                                                 <th>Status</th>
                                                  <th width="150px">Buttons</th>
                                                  </tr>
                                                </thead>
                                                <tbody>
                                     {% for order in orders %}
                                    {% if order.order.order_status == '0' %}
                                           <tr class="gradeX">
                                               <td>{{ order.order.id }}</td>
<!--                                                 <td>{{ user.id }}</td>-->
                                                    <td>{{ order.order.from_location }}</td>
                                                     <td>{{ order.order.to_location }}</td>
                                                     <td>{{ order.order.product_type }}</td>
                                                     <td>{{ order.order.Date }}</td>
<!--                                                     <td>{{ order.payment_option }}</td>-->
                                      {% if order.order.order_status == '1' %}
                                           <td><span class="badge">{{ order.order.order_status }}</span></td>
                                            {% elif order.order.order_status == '0' %}
                                           <td><span class="badge" style="background: #ff9800"> {{ order.order.order_status }}</span></td>

                                             {% endif %}
                                    <td>

                                     <a href="{% url 'delivery_service:delivery_destroy' order.id %}" class="btn ink-reaction btn-floating-action btn-danger" onclick="return confirm('Are you sure you want to delete this?')"><i class="md md-delete"></i> </a>
                                      <a href="{% url 'delivery_service:edit_delivery' order.id %}" class="btn ink-reaction btn-floating-action btn-warning"><i class="md md-edit"></i> </a>

                                     <a href="{% url 'delivery_service:show' order.id %}" class="btn ink-reaction btn-floating-action btn-primary"><i class="md md-print"></i> </a>


<!--                                <a href="{% url 'delivery_service:see' order.id%}" class="btn ink-reaction btn-floating-action btn-send"><i class="md md-send"></i> </a>-->


                                    </td>
                       </tr>
                                     {% endif %}
                         {% endfor %}

                  </tbody>

               </table>

        </div><!--end .table-responsive -->

     </div>

    </div>

   </div><!--end .col -->

   </div><!--end .row -->

      <!-- END DATATABLE 2 -->

</div><!--end .section-body -->

    </section>
{% endblock %}

e_courier/delivery_service/templates/delivery_detail_view.html
{% extends 'layout.html' %}

{% load widget_tweaks %}

{% block body %}

<div class="container">
<div class="row">

  <div class="column">
    <div class="card">
      <!-- <img src="/w3images/team1.jpg" alt="Jane" style="width:100%"> -->
      <div class="container">
        <form action="" method="post">
          {% csrf_token %}
        <h2>Name : {{user.username}}</h2>
        <p class="title">From Location: {{obj.from_location}}</p>
        <p class="title">To Location: {{obj.to_location}}</p>
        <p>Product Type is : {{obj.product_type}}</p>
        <input type="hidden" name="object" value="{{ obj.id }}">
        <input type="hidden" name="user" value="{{ user.id }}">
        <a href=""><button type="submit" name="send" class="button">Send</button></a>
        <a href="#"><button type="submit" name="reject" class="button">Reject</button></a>
        </form>
      </div>
    </div>
  </div>

  </div>
</div>
{% endblock %}

e_courier/delivery_service/templates/driver_choose_present_location.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}

<style>
    body{
        color: black;
        background: black;

	}

</style>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Bootstrap Table with Add and Delete Row Feature</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <style>

button{
    align-items:center;
}
    </style>
    <body>
<br>
<br>
<hr>
<a href="{% url 'delivery_service:send' %}"><button type="button" class="btn btn-success btn-lg btn-block">For Naraungonj Zone</button></a><br><hr>
<a href="{% url 'delivery_service:GazipurZone' %}"><button type="button" class="btn btn-light btn-lg btn-block">For Gazipur Zone</button></a><br><hr>
<a href="{% url 'delivery_service:BonaniZone' %}"><button type="button" class="btn btn-warning btn-lg btn-block">For Bonani Zone</button></a><br><hr>

</body>




{% endblock %}

e_courier/delivery_service/templates/tracker.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
<script src='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.css' rel='stylesheet' />

<style>
    body{
        color: black;
        background: black;

	}

</style>


<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Sign Up</title>

    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css'%}" rel="stylesheet" media="all">
</head>



  <div class="container">
    <div class="col my-4">
        <h2>Enter your Delivery Id and Phone Number to track your delivery</h2>
        <form method="post" action="#" id="trackerForm">{% csrf_token %}





            <div class="page-wrapper bg-dark p-t-100 p-b-50">
        <div class="wrapper wrapper--w900">
            <div class="card card-6">
                <div class="card-heading">
                    <h2 class="title">Track Your Delivery</h2>
                </div>
                <div class="card-body">




                    <form method="POST" action="{% url 'accounts:signup' %}"novalidate>
                        {% csrf_token %}
                        <div class="form-row">

                            <div class="name">Order Id</div>
                            <div class="value">
                                <input class="input--style-6" type="text" name="orderId" placeholder="Order Id">
                            </div>
                        </div>




<!--                           <div class="form-row">-->
<!--                               <div class="name">Phone Number</div>-->
<!--                            <div class="value">-->
<!--                                <input class="input&#45;&#45;style-6" type="text" name="phone" placeholder="Phone">-->
<!--                            </div>-->
<!--                        </div>-->






                         <div class="card-footer">

                     <input class="btn btn--radius-2 btn--blue-2" type="submit" value="Track your Delivery Location" >

                </div>
                    </form>
                </div>

            </div>
        </div>
    </div>






        </form>
    <div class="col my-4">
        <h2>Your Delivery Status</h2>
        <div class="my-4">
            <ul class="list-group" id="items">
            	Enter your Delivery Id and click Track Order to find details about your order!
            </ul>
        </div>
    </div>
    </div>
    </div>

<div id='map' style='width: 100%; height: 400px;'></div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
   <script>
$('#trackerForm').submit(function(event) {
    $('#items').empty();
    var formData = {
        'orderId': $('input[name=orderId]').val(),
        'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val()
    };
    $.ajax({
            type: 'POST',
            url: '{% url 'delivery_service:tracker' %}',
            data: formData,
            encode: true
        })
        .done(function(data) {
            console.log(data)
            updates = JSON.parse(data);
            if (updates.length > 0 & updates != {}) {
                for (i = 0; i < updates.length; i++) {
                    let text = updates[i]['text'];
                    let number = updates[i]['number'];
                    let time = updates[i]['time'];

                    mystr = `<li class="list-group-item disabled justify-content-between align-items-center">
                    Longitude = ${number}  and Latitude =  ${text}
                    <span class="badge badge-primary badge-pill">${time}</span>
                </li>`
                    $('#items').append(mystr);


mapboxgl.accessToken = 'pk.eyJ1IjoibGFib25pIiwiYSI6ImNrMWk0Zmh3aTBhenczbnJwNDVkeWZ2dGwifQ.zsuot2lnIegDVPdKKeBM4Q';
            var map = new mapboxgl.Map({
            container: 'map',

            style: "mapbox://styles/mapbox/satellite-streets-v11",
            center: [text,number], // starting position [lng, lat]
           zoom: 10, // starting zoom
            });


map.on("load", function () {
/* Image: An image is loaded and added to the map. */
map.loadImage("https://i.imgur.com/MK4NUzI.png", function(error, image) {
if (error) throw error;
map.addImage("custom-marker", image);
/* Style layer: A style layer ties together the source and image and specifies how they are displayed on the map. */
map.addLayer({
id: "markers",
type: "symbol",
/* Source: A data source specifies the geographic coordinate where the image marker gets placed. */
source: {
type: "geojson",
data: {
type: 'FeatureCollection',
features: [
{
type: 'Feature',
properties: {},
geometry: {
type: "Point",
coordinates: [text,number]
}
}
]
}
},
layout: {
"icon-image": "custom-marker",
}
});
});
});


                }
            } else {
            	mystr = `<li class="list-group-item disabled justify-content-between align-items-center">
                    Sorry, We are not able to fetch this delivery id. Make sure to type correct delivery Id</li>`
            	$('#items').append(mystr);
            }
        });
    event.preventDefault();

});







</script>




    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>


    <!-- Main JS-->
    <script src="{% static 'js/global.js'%}"></script>


 <!--   start copyright text area-->
    <div class="copyright-area">
        <div class="container">
            <div class="col-xs-12 col-sm-6 col-md-6 text-left">
                <div class="footer-text">

                </div>
            </div>
            <div class="col-xs-12  col-sm-6 col-md-6 text-right">
                <div class="footer-text">
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="#" class="fa fa-twitter"></a>
                    <a href="#" class="fa fa-linkedin"></a>
                    <a href="#" class="fa fa-google-plus"></a>
                    <a href="#" class="fa fa-dribbble"></a>
                </div>
            </div>
        </div>
    </div>
    <!--    end of copyright text area-->
{% endblock%}