e_courier/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name='accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp, name='signup'),

    # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('help/', views.help.as_view(), name='help'),
    path('SearchResultsView/', views.SearchResultsView, name='SearchResultsView'),
    path('totalBill/', views.totalBill, name='totalBill'),
    path('customer_service/', views.customer_service.as_view(), name='customer_service'),
    path('all_delivery_for_show_user/', views.all_delivery_for_show_user, name='all_delivery_for_show_user'),
    path('client_see_driver_details/', views.client_see_driver_details, name="client_see_driver_details"),
    path('charge/<int:delivery_id>/', views.charge, name="charge"),
    path('rating_enter/<int:order_id>/', views.rating_enter, name="rating_enter"),
]

e_courier/delivery_service/urls.py
from django.urls import path
from .import views
from .views import(
   delivery_request,
   wait_sms
)
app_name='delivery_service'
urlpatterns = [
      path('', views.delivery_request, name='delivery_request'),
      # path('sms_send/', views.sms_send, name='sms_send'),
      path('wait_sms/',views.wait_sms,name='wait_sms'),
      path('all_delivery/',views.all_delivery,name='all_delivery'),
      path('tracker/',views.tracker,name='tracker'),
      path('all_latest_delivery_order/',views.all_latest_delivery_order,name='all_latest_delivery_order'),
      path('show/<order_id>/',views.show,name='show'),
      # path('edit_delivery/<int:order_id>/',views.edit_delivery,name="edit_delivery" ),
      path('edit_delivery/<order_id>/', views.edit_delivery,name='edit_delivery'),
      # path('update_delivery/<order_id>/', views.update_delivery,name='update_delivery'),
      path('DeliveryDetail/<int:id>/',views.DeliveryDetail,name="DeliveryDetail" ),
      path('delivery_destroy/<order_id>/',views.delivery_destroy,name="delivery_destroy" ),
      path('cancel_ride/',views.cancel_ride,name="cancel_ride" ),

      path('see/<int:my_id>/', views.see, name='see'),
      path('send/', views.send, name='send'),

      path('delivery_track_update/', views.delivery_track_update, name='delivery_track_update'),
      path('delivery_track_add/', views.delivery_track_add, name='delivery_track_add'),
      path('ClientChart/', views.ClientChart.as_view(), name='ClientChart'),
      path('GazipurZone/', views.GazipurZone, name='GazipurZone'),
      path('BonaniZone/', views.BonaniZone, name='BonaniZone'),
      path('click_for_send_driver_details/<int:my_id>/', views.click_for_send_driver_details, name='click_for_send_driver_details'),
      path('client_see_driver_details/<int:request_id>/', views.client_see_driver_details, name='client_see_driver_details'),
      path('driver_choose_present_location/',views.driver_choose_present_location,name="driver_choose_present_location"),
   ]

e_courier/driver/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name="driver"
urlpatterns = [
      path('', views.Active_driver, name='Active_driver'),
      path('driver/', views.driver, name='driver'),
      path('driver_form/', views.driver_form,name='driver_form'),
      path('edit/<id>/', views.edit,name='edit'),
      path('update/<id>/', views.update,name='update'),

      path('driver_login/', auth_views.LoginView.as_view(template_name='account/driver_login.html'), name='driver_login'),#driver
      path('logout/', auth_views.LogoutView.as_view(), name='logout'),
      
      path('DriverSignUp/', views.DriverSignUp, name='DriverSignUp'),#driver
      
      path('driver_profile_page/', views.driver_profile_page, name='driver_profile_page'),#driver
      path('driver_see_the_request/', views.driver_see_the_request.as_view(template_name='tasks.html'), name='driver_see_the_request'),

      # path('DeliveryUpdate/<int:id>/',views.DeliveryUpdate.as_view(),name="DeliveryUpdate" ),
      path('driver_see_delivery_details/',views.driver_see_delivery_details,name="driver_see_delivery_details" ),
      # path('ForShareLocation/',views.ForShareLocation,name="ForShareLocation"),
      path('livelocationshare/<int:id>/',views.livelocationshare,name="livelocationshare"),
      path('locationUpdate/<int:order_id>/',views.locationUpdate,name="locationUpdate"),
      path('ViewMapLocation/<int:id>/',views.ViewMapLocation,name="ViewMapLocation"),
]

e_courier/e_courier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account import views as user_views
from .import views

from django.contrib.staticfiles.templatetags.staticfiles import static as staticfiles
from django.utils.translation import ugettext_lazy as _
from material.admin.sites import site

admin.site.site_header = ('Sample Delivery')
admin.site.site_title = ('Sample Delivery')
admin.site.index_title = ('Sample Delivery')


urlpatterns = [
    # path('admin/', include('material.admin.urls')),
    path('admin/', admin.site.urls),
    path('profile/',user_views.profile, name='profile'),
    path('home',views.HomePage,name='home'),
    path('AboutPage/',views.AboutPage.as_view(),name='AboutPage'),
    path('account/', include('account.urls',namespace="account")),
    path('account/', include('django.contrib.auth.urls')),
    path('delivery_service/', include('delivery_service.urls')),
    path('Factory/', include('factoryHead.urls')),
    # path('notification/', include('notification.urls')),
    path('', include('driver.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThankstPage.as_view(), name='thanks'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_courier/account/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.db.models.signals import post_save
from django.urls import reverse

from industry.models import IndustryName


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # email = models.EmailField(max_length=70,unique=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    factoryName = models.ForeignKey(IndustryName, null=True,on_delete=models.CASCADE, related_name='FactoryName')

    def __str__(self):
        return f'{self.user.username}  and  {self.factoryName}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class contact(models.Model):
    factoryname = models.CharField(max_length=50)
    email = models.EmailField()
    Message = models.TextField()
    def __str__(self):
        return self.factoryname
class CommentBox(models.Model):
    name = models.TextField()

e_courier/account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from .models import Profile, contact, CommentBox

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError("'Your email is already in our list of users to be notified.Try a new email")
        return self.cleaned_data
    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

class ContactForm(forms.ModelForm):
    class Meta:
        model = contact
        fields = ['factoryname', 'email', 'Message']

class commentboxform(forms.ModelForm):
    class Meta:
        model = CommentBox
        fields = ['name']

e_courier/account/views.py
from django.db.models import Q
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse, get_object_or_404
from django.conf import settings
import stripe
import json
from django.views import View
from django.views.generic import ListView
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import JsonResponse
from django.urls import reverse_lazy
from sympy.physics.units import cd

from delivery_service.forms import DelevaryInfoForm
from industry.models import PriceSet, Industry
from .models import Profile, contact
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView,TemplateView,DetailView
# Create your views here.
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm, ContactForm
from delivery_service.models import DeliveryProduct, DelevaryInfo
from django.urls import reverse
from django.contrib.auth import authenticate
from django.db.models import Sum,Count


stripe.api_key = settings.STRIPE_SECRET_KEY

@login_required
def all_delivery_for_show_user(request):
    orders = DelevaryInfo.objects.filter().order_by('-id')
    # orders = delivery_product.objects.filter().order_by('-Date')
    return render(request, 'accounts/delivery_details_show_for_user.html', {'orders': orders})
def login(request):
    if request.method =="POST":
        # username = request.POST.get('username')
        username = request.POST.get('username')
        password = request.POST.get('password')
        user =authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not create")
        else:
            print("Someone tried to login and falied!")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'login.html', {})

def SignUp(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'accounts/signup.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        print(request.user)
        profile_, _ = Profile.objects.get_or_create(user=request.user)
        print(profile_)
        p_form = ProfileUpdateForm(instance=profile_)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'accounts/profile.html', context)

class help(TemplateView):
    template_name = 'accounts/help.html'


class customer_service(View):
    def get(self, request):
        return render(request,'accounts/customer_service.html')
    def post(self, request):
        print(request.POST)
        factoryname = request.POST.get('factoryname')
        email = request.POST.get('email')
        Message = request.POST.get('Message')
        book_details = contact(factoryname=factoryname, email=email, Message=Message)
        book_details.save()
        return redirect('/home')


def client_see_driver_details(request):
    order = DelevaryInfo.objects.filter().order_by('-id')
    key = settings.STRIPE_PUBLISHABLE_KEY
    return render(request, 'accounts/client_see_driver_details.html', {'order': order, 'key': key})



@login_required
def rating_enter(request, order_id):
    order = DelevaryInfo.objects.get(id=order_id)
    if request.POST:
        form = DelevaryInfoForm(request.POST, instance=order)
        if form.is_valid():
            if form.save():
                return redirect(reverse('accounts:client_see_driver_details'), messages.success(request, 'Successfully rating create', 'alert-success'))
            else:
                return redirect(reverse('accounts:client_see_driver_details'), messages.error(request, 'Data is not saved', 'alert-danger'))
        else:
            return redirect(reverse('accounts:client_see_driver_details'), messages.error(request, 'Form is not valid', 'alert-danger'))
    else:
        form = DelevaryInfoForm(instance=order)
        return render(request, 'accounts/driver_rating_create.html', {'form': form})

def charge(request, delivery_id):
    order = DelevaryInfo.objects.get(id=delivery_id)
    price = PriceSet.objects.get(id=order.industry_id)
    if request.method == 'POST':
        print(price.price)
        charge =stripe.Charge.create(
            amount=str(price.price),
            currency='usd',
            description='Courier Payment',
            source=request.POST['stripeToken'],
        )
    return render(request,'accounts/charge.html', {'order': order})

def totalBill(request):
    total = DelevaryInfo.objects.all()
    order = []
    for delivery_info in total:
        print(delivery_info.client.user)
        if delivery_info.client.user == request.user:
            if delivery_info.order.order_status == '0':
                print(delivery_info.client)
                order += [delivery_info.industry.price]
    print(order)
    sum = 0
    for i in range(len(order)):
        sum+=order[i]
    print(sum)
    result = DelevaryInfo.objects.values('client').order_by('client').annotate(count=Count('client')).annotate(total_price=Sum('industry'))
    return render(request,'accounts/totalBill.html', {'result': result, 'total': total,'sum': sum})

@login_required
def SearchResultsView(request):
    queryset_list = PriceSet.objects.all()
    # import pdb;
    # pdb.set_trace()
    query = request.GET.get("q")

    if query:
        queryset_list=queryset_list.filter(
            Q(location1__icontains=query) |
            Q(location2__icontains=query)
        ).distinct()
    paginator = Paginator(queryset_list, 4)  # Show 25 contacts per page
    page_request_var = "pageList"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)
    context={
        "object_list": queryset,
        "title": "List",
        "page_request_var": page_request_var
    }
    return render(request, "accounts/priceSet.html", context)

e_courier/account/templates/accounts/charge.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<style>
    body{
        color: white;
        background: black;

	}

</style>
<h2>Successfully accept your <strong>Bill</strong>!</h2>
{% endblock %}

e_courier/account/templates/accounts/client_see_driver_details.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% load static%}
{% block content %}
<style>
    body{
        color: white;
        background: black;

	}

</style>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>history</title>

    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css'%}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-dark p-t-100 p-b-50">

            <div class="card card-6">
                <div class="card-heading">
                    <h2 class="title">Driver list who accept the <b>delivery request</b></h2>
                </div>

                <div class="card-body">


                 <table id="datatable2" class="table order-column hover">
                                      <thead>
                    <tr>
                        <th><i class="fa fa-map-marker"></i>AWB</th>
                        <th><i class="glyphicon glyphicon-road"></i> From </th>
                        <th><i class="glyphicon glyphicon-road"></i> Destination </th>
                        <th><i class="glyphicon glyphicon-eye-open"></i> Product Type</th>
                        <th><i class="glyphicon glyphicon-time"></i> Date</th>
                        <th><i class="glyphicon glyphicon-user"></i> Driver Name</th>
                        <th><i  class="glyphicon glyphicon-phone-alt"></i> Driver PhoneNumber</th>
                        <th><i  class="glyphicon glyphicon-bed"></i> Car details</th>
                        <th><i  class="glyphicon glyphicon-usd"></i> Pay</th>
                        <th><i  class="glyphicon glyphicon-star"></i> Please Enter Driver Rating</th>
                    </tr>
                </thead>
                                                <tbody>
                                       {% for orders in order %}

   {% if orders.client.user == request.user %}
        <tr class="gradeX">
            <td>{{orders.order.id}} and {{orders.order.phone}}</td>
         <td>{{orders.order.from_location}}</td>
         <td>{{ orders.order.to_location }}</td>
         <td>{{ orders.order.product_type }}</td>
         <td>{{ orders.order.Date }}</td>
         <td>{{ orders.driver.user }}</td>
         <td>{{ orders.driver.phone }}</td>
         <td>{{ orders.driver.car_details }}</td>
            <td>
                <h5>{{ orders.industry.price }}</h5>
<!--                <h5>{{ orders.order.Bill }}</h5>-->
      {% if orders.order.order_status == '0' %}
     <form action="{% url 'accounts:charge' orders.id %}"method="POST">
		{% csrf_token %}
<script src="https://checkout.stripe.com/checkout.js"class="stripe-button"
		data-key = "{{key}}"
		data-description = "please pay {{ orders.industry.price }}tk"
		data-amount="{{orders.industry.price}}"
		data-location="auto"
        data-name="Courier payment"
        data-description = "pay"
        data-image="https://stripe.com/img/docummnetation/checkout/marketplace.png"
		data-email="">
</script>
         {% endif %}
           <script>
    $(() => {
      var handler = StripeCheckout.configure({
        key: '{{ key }}',
        locale: 'auto',
        token: function(token) {
          $('.notification-success-wrapper').css('display', 'none');
          $('.notification-danger-wrapper').css('display', 'none');
          $.ajax({
            url: '/courses/charge/',
            method: 'POST',
            data: JSON.stringify({
              token: token.id,
              amount: "{{ course.price }}" * 100,
              description: "{{ course.title }}",
              course_id: "{{ course.id }}",
            }),
            headers: {'X-CSRFToken': generated_csrf_token},
          })
          .done((res) => {
            const message = 'Thanks for purchasing!'
            $('div > .notification.is-success').html(message);
            $('.notification-success-wrapper').css('display', 'block');
          })
          .fail((err) => {
            const message = 'There was a problem processing your payment. Please use a different payment method or contact your payment method provider.<br><br>Please contact us if you continue to have problems.'
            $('div > .notification.is-danger').html(message);
            $('.notification-danger-wrapper').css('display', 'block');
          });
        }
      });
      document.getElementById('purchase-btn').addEventListener('click', function(e) {
        // Open Checkout with further options:
        handler.open({
          name: "Purchase a course",
          description: "{{ user.email }}",
          amount: "{{ course.price }}" * 100
        });
        e.preventDefault();
      });
      // Close Checkout on page navigation:
      window.addEventListener('popstate', function() {
        handler.close();
      });
    });
  </script>
</form>
  </td>
            <td>

{{orders.rating}}
                {% if orders.rating == '1' %}
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>

                {% elif orders.rating == '2' %}
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>

                {% elif orders.rating == '3' %}
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star checked" style="color:yellow"></span>
                <span class="fa fa-star"></span>
                <span class="fa fa-star"></span>
                {% elif orders.rating ==  '4' %}
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star"></span>
                {% else %}
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star checked"style="color:yellow"></span>
                <span class="fa fa-star checked"style="color:yellow"></span>
                {% endif %}
<a href="{% url 'accounts:rating_enter' orders.id%}"><button >Update Rating</button></a>

            </td>
</tr>
   {% endif %}
{% endfor %}

                  </tbody>

               </table>

                </div>
            </div>
        </div>



    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>


    <!-- Main JS-->
    <script src="{% static 'js/global.js'%}"></script>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>
<!-- end document-->




{% endblock %}

e_courier/account/templates/accounts/help.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
<h1>This is our help page</h1>
</div>
{% endblock %}

e_courier/account/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
<style>
    body{
        color: black;
        background: black;

	}

</style>
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
        <a href="{% url 'password_reset' %}">Forgot Your Password?</a>
    </form>
</div>
<br>

{% endblock %}

e_courier/account/templates/accounts/profile.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    body{
        color: black;
        background: black;

	}

</style>


<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Sign Up</title>

    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css'%}" rel="stylesheet" media="all">
</head>







<div class="container">
    <div class="row profile">
		<div class="col-md-3">
			<div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
				<img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						Hi {{ user.username }}
					</div>
				</div>
				<!-- END SIDEBAR USER TITLE -->
				<!-- SIDEBAR BUTTONS -->
				<div class="profile-userbuttons">
					<button type="button" class="btn btn-success btn-sm">{{ user.email }}</button>
				</div>
				<!-- END SIDEBAR BUTTONS -->
				<!-- SIDEBAR MENU -->
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="active">
							<a href="{% url 'accounts:all_delivery_for_show_user'%}">
							<i class="glyphicon glyphicon-home"></i>
							History </a>
						</li>
						<li>
							<a href="{% url 'password_change'%}">

							<i class="glyphicon glyphicon-user"></i>
							Change My Password </a>
						</li>
						<li>
							<a href="{% url 'accounts:client_see_driver_details' %}" target="_blank">
							<i class="glyphicon glyphicon-send"></i>
							See Driver details</a>
						</li>
						<li>
							<a href="{% url 'accounts:SearchResultsView' %}" target="_blank">
							<i class="glyphicon glyphicon-usd"></i>
							Check Destination Price </a>
						</li>

						<li class="active">
							<a href="{% url 'delivery_service:tracker'%}">
							<i class="glyphicon glyphicon-map-marker"></i>
							Track Your delivery</a>
						</li>

						<li class="active">
							<a href="{% url 'accounts:totalBill'%}">
							<i class="glyphicon glyphicon-usd"></i>
							Your Total Bill</a>
						</li>
					</ul>
				</div>
				<!-- END MENU -->
			</div>
		</div>
		<div class="col-md-9">
            <div class="profile-content">

				<div class="page-wrapper bg-dark p-t-100 p-b-50">
        <div class="wrapper wrapper--w900">
            <div class="card card-6">
                <div class="card-heading">
                    <h2 class="title">Update Your Profile</h2>
                </div>
                <div class="card-body">

         <form method="post"enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row">

                            <div class="name">Username</div>
                            <div class="value">
								{{ u_form.username|as_crispy_field }}
                            </div>
                        </div>


                           <div class="form-row">
                               <div class="name">Email address</div>
                            <div class="value">
                                {{ u_form.email|as_crispy_field }}
                            </div>
                        </div>

                           <div class="form-row">
                               <div class="name">Choose File</div>
                            <div class="value">
								{{ p_form.image|as_crispy_field }}
                            </div>
                        </div>



                         <div class="card-footer">

                     <input class="btn btn--radius-2 btn--blue-2" type="submit" value="Update" >

                </div>
                    </form>

					    </div>

            </div>
        </div>
    </div>


            </div>
		</div>
	</div>
</div>
<br>
<br>



{% block client_see_driver_details %}

{% endblock %}

    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>


    <!-- Main JS-->
    <script src="{% static 'js/global.js'%}"></script>


 <!--   start copyright text area-->
    <div class="copyright-area">
        <div class="container">
            <div class="col-xs-12 col-sm-6 col-md-6 text-left">
                <div class="footer-text">

                </div>
            </div>
            <div class="col-xs-12  col-sm-6 col-md-6 text-right">
                <div class="footer-text">
                    <a href="#" class="fa fa-facebook"></a>
                    <a href="#" class="fa fa-twitter"></a>
                    <a href="#" class="fa fa-linkedin"></a>
                    <a href="#" class="fa fa-google-plus"></a>
                    <a href="#" class="fa fa-dribbble"></a>
                </div>
            </div>
        </div>
    </div>
    <!--    end of copyright text area-->
{% endblock %}

e_courier/account/templates/accounts/totalBill.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block content %}
<html>
<head>
<style>
body{
        color: white;
        background: black;

	}
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: black;
}
</style>
</head>
<body>

<h2>Total Bill</h2>

<table>
  <tr>
    <th>Client Name</th>
    <th>All Bill</th>
     <th>Total Bill</th>
  </tr>

  <tr>
    <td>{{request.user}}</td>
    <td>{% for order in total %}
       {% if order.client.user == request.user %}
         {% if order.order.order_status == '0' %}
    <h6>{{order.industry.price}}</h6>
       {% endif %}
         {% endif %}
    {% endfor %}</td>
    <td>{{sum}}</td>

  </tr>
</table>
</body>
</html>
{% endblock %}