e_courier/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name='accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp, name='signup'),

    # path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('help/', views.help.as_view(), name='help'),
    path('SearchResultsView/', views.SearchResultsView, name='SearchResultsView'),
    path('totalBill/', views.totalBill, name='totalBill'),
    path('customer_service/', views.customer_service.as_view(), name='customer_service'),
    path('all_delivery_for_show_user/', views.all_delivery_for_show_user, name='all_delivery_for_show_user'),
    path('client_see_driver_details/', views.client_see_driver_details, name="client_see_driver_details"),
    path('charge/<int:delivery_id>/', views.charge, name="charge"),
    path('rating_enter/<int:order_id>/', views.rating_enter, name="rating_enter"),
]

e_courier/delivery_service/urls.py
from django.urls import path
from .import views
from .views import(
   delivery_request,
   wait_sms
)
app_name='delivery_service'
urlpatterns = [
      path('', views.delivery_request, name='delivery_request'),
      # path('sms_send/', views.sms_send, name='sms_send'),
      path('wait_sms/',views.wait_sms,name='wait_sms'),
      path('all_delivery/',views.all_delivery,name='all_delivery'),
      path('tracker/',views.tracker,name='tracker'),
      path('all_latest_delivery_order/',views.all_latest_delivery_order,name='all_latest_delivery_order'),
      path('show/<order_id>/',views.show,name='show'),
      # path('edit_delivery/<int:order_id>/',views.edit_delivery,name="edit_delivery" ),
      path('edit_delivery/<order_id>/', views.edit_delivery,name='edit_delivery'),
      # path('update_delivery/<order_id>/', views.update_delivery,name='update_delivery'),
      path('DeliveryDetail/<int:id>/',views.DeliveryDetail,name="DeliveryDetail" ),
      path('delivery_destroy/<order_id>/',views.delivery_destroy,name="delivery_destroy" ),
      path('cancel_ride/',views.cancel_ride,name="cancel_ride" ),

      path('see/<int:my_id>/', views.see, name='see'),
      path('send/', views.send, name='send'),

      path('delivery_track_update/', views.delivery_track_update, name='delivery_track_update'),
      path('delivery_track_add/', views.delivery_track_add, name='delivery_track_add'),
      path('ClientChart/', views.ClientChart.as_view(), name='ClientChart'),
      path('GazipurZone/', views.GazipurZone, name='GazipurZone'),
      path('BonaniZone/', views.BonaniZone, name='BonaniZone'),
      path('click_for_send_driver_details/<int:my_id>/', views.click_for_send_driver_details, name='click_for_send_driver_details'),
      path('client_see_driver_details/<int:request_id>/', views.client_see_driver_details, name='client_see_driver_details'),
      path('driver_choose_present_location/',views.driver_choose_present_location,name="driver_choose_present_location"),
   ]

e_courier/driver/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .import views
app_name="driver"
urlpatterns = [
      path('', views.Active_driver, name='Active_driver'),
      path('driver/', views.driver, name='driver'),
      path('driver_form/', views.driver_form,name='driver_form'),
      path('edit/<id>/', views.edit,name='edit'),
      path('update/<id>/', views.update,name='update'),

      path('driver_login/', auth_views.LoginView.as_view(template_name='account/driver_login.html'), name='driver_login'),#driver
      path('logout/', auth_views.LogoutView.as_view(), name='logout'),
      
      path('DriverSignUp/', views.DriverSignUp, name='DriverSignUp'),#driver
      
      path('driver_profile_page/', views.driver_profile_page, name='driver_profile_page'),#driver
      path('driver_see_the_request/', views.driver_see_the_request.as_view(template_name='tasks.html'), name='driver_see_the_request'),

      # path('DeliveryUpdate/<int:id>/',views.DeliveryUpdate.as_view(),name="DeliveryUpdate" ),
      path('driver_see_delivery_details/',views.driver_see_delivery_details,name="driver_see_delivery_details" ),
      # path('ForShareLocation/',views.ForShareLocation,name="ForShareLocation"),
      path('livelocationshare/<int:id>/',views.livelocationshare,name="livelocationshare"),
      path('locationUpdate/<int:order_id>/',views.locationUpdate,name="locationUpdate"),
      path('ViewMapLocation/<int:id>/',views.ViewMapLocation,name="ViewMapLocation"),
]

e_courier/e_courier/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from account import views as user_views
from .import views

from django.contrib.staticfiles.templatetags.staticfiles import static as staticfiles
from django.utils.translation import ugettext_lazy as _
from material.admin.sites import site

admin.site.site_header = ('Sample Delivery')
admin.site.site_title = ('Sample Delivery')
admin.site.index_title = ('Sample Delivery')


urlpatterns = [
    # path('admin/', include('material.admin.urls')),
    path('admin/', admin.site.urls),
    path('profile/',user_views.profile, name='profile'),
    path('home',views.HomePage,name='home'),
    path('AboutPage/',views.AboutPage.as_view(),name='AboutPage'),
    path('account/', include('account.urls',namespace="account")),
    path('account/', include('django.contrib.auth.urls')),
    path('delivery_service/', include('delivery_service.urls')),
    path('Factory/', include('factoryHead.urls')),
    # path('notification/', include('notification.urls')),
    path('', include('driver.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThankstPage.as_view(), name='thanks'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_courier/templates/about.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
<style>
<!--.right {-->
<!--  position: absolute;-->
<!--  right: 60px;-->
<!--  width: 400px;-->
<!--  padding: 10px;-->
<!--}-->
body{
        color: black;
        background: black;

	}


</style>

<div class="row">
    <div class="col-sm-10">
     <h2 class="contact-title" style="color:white;">About Us</h2>
     </div>
     <div class="col-lg-8">
 <p style="color:white;">We decided to establish a web app for RMG industries.Our motive is learning about an very
     effective and efficient technology of Courier service of different samples for ready made garments
     factories in Bangladesh.We proposed this technique to add some value for ready made garments factory
     where sample transaction occurs in a daily basis as RMG is the  biggest revenue earning industry in our
     country.We choose to develop the delivery of samples because of sampling is the 1st key element to
     get bulk order.Though sample delivery is must here, it follows a traditional and poor intra sample
     delivery system between factories and buying offices.So our technique can bring some possible solutions
     to overcome these problem.Buyers & sellers can track their samples anytime from anywhere which will reduce
     mental stress & improve the transparency of products.There will be no needed of excessive people & costs for
     factories to handle samples delivery.Factories can get total buyer wise samples sending data,costs &
     what’s return for better decision making.Sample can be sent anytime,no need stick to one or two times
     which will safe time.So saving time,reducing stresses and give transparency are prime concern of our system .
     We decided to work with this according to demand of time in ready made garments factory in Bangladesh.
     In our project,the whole system deals with giving the service to customers(i.e  merchandisers,buying
     house officers) and response to a delivery request of registered drivers.We have more plans of some features
     to implement further.We will try with our best effort to
     make this technique as reliable as possible and also put sincerity to make sense of our system.</p>
         <img class="right" src="{% static 'img/courier-checking-package-for-courier.jpg' %}"align="middle">




     </div>

                </div>

{% endblock %}

e_courier/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Fast Delivery</title>
    <!--  bootstrap css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!--  font Awesome Css  -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    <!--    stylesheet for fonts-->
    <link href="{% static 'fonts/stylesheet.css'%}" rel="stylesheet">
    <!-- Reset css-->
    <link href="{% static 'css/reset.css'%}" rel="stylesheet">

    <!--slick css-->
    <link href="{% static 'css/slick.css'%}" rel="stylesheet">
    <!--  owl-carousel css -->
    <link href="{% static 'css/owl.carousel.css'%}" rel="stylesheet">
    <!--  YTPlayer css For Background Video -->
    <link href="{% static 'css/jquery.mb.YTPlayer.min.css'%}" rel="stylesheet">
    <!--  style css  -->
    <link rel="stylesheet" href="{% static 'css/meanmenu.css'%}">
    <link href="{% static 'style.css'%}" rel="stylesheet">
    <!--  Responsive Css  -->
    <link href="{% static 'css/responsive.css'%}" rel="stylesheet">

    <!--  browser campatibel css files-->
    <!--[if lt IE 9]>
        <script src="{% static '//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'%}"></script>
        <script src="{% static '//oss.maxcdn.com/respond/1.4.2/respond.min.js'%}"></script>
    <![endif]-->
</head>

<body class="js">

    <!--start header area-->

            <div class="container">
                <div class="row">
                    <div class="col-md-2 col-lg-2 col-sm-2 col-xs-6">
                        <div class="logo">
  <a href="#"><img src="{% static 'img/Untitled-4.png'%}" alt="logo"></a>
                        </div>
                    </div>


                    <div class="col-md-6 col-xs-6 col-md-offset-1 col-sm-7 col-lg-offset-1 col-lg-6 mobMenuCol">
                        <nav class="navbar">
                            <!-- Collect the nav links, forms, and other content for toggling -->
                                <ul class="nav navbar-nav navbar-right menu">
                                    {% if user.is_authenticated %}
                                    <li class="current-menu-item"><a href="">Sample Delivery<span class="caret"></span></a>
                                       <ul class="dropdownMenu">
                                           <li><a href="{% url 'home' %}">Home</a></li>
                                           <li><a href="{% url 'AboutPage' %}">About Us</a></li>
                                           <li><a href="{% url 'accounts:customer_service' %}">Contact</a></li>
                                           <li><a href="{% url 'delivery_service:tracker'%}">Track your delivery</a></li>

                                       </ul>

                                    </li>

                                    <li><a href="{% url 'delivery_service:delivery_request' %}">Delivery services</a></li>
                                    <li><a href="{% url 'profile' %}">Profile</a></li>
                                    <li><a href="{% url 'driver:driver_profile_page' %}">Driver Profile</a></li>




                                </ul>
                            <!-- /.navbar-collapse -->
                        </nav>
                    </div>

                    <div class="col-md-3 col-sm-3 col-xs-4 col-lg-3 signup">
                        <ul class="nav navbar-nav">
                             <li><a href="{% url 'accounts:logout' %}">logOut</a></li>

                            <li><a href="{% url 'accounts:signup' %}">sign up</a></li>
<!--                            <li><a href="{% url 'driver:DriverSignUp' %}">sign up</a></li>-->
                        </ul>





                        {% else %}


                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'AboutPage' %}">About Us</a></li>
                        <li><a href="{% url 'accounts:customer_service' %}">Contact</a></li>

                                </ul>
                            <!-- /.navbar-collapse -->
                        </nav>
                    </div>

                    <div class="col-md-3 col-sm-3 col-xs-4 col-lg-3 signup">
                        <ul class="nav navbar-nav">

                            <li><a href="{% url 'accounts:login' %}">login</a></li>
                            <li><a href="{% url 'accounts:signup' %}">sign up</a></li>
<!--                             <li><a href="{% url 'driver:DriverSignUp' %}">sign up</a></li>-->
                        </ul>

                        {% endif%}
                    </div>
                </div>
            </div>


    <!--end of header area-->

   <div class="container">
  {% block content %}

  {% endblock %}

</div>




<!--     &lt;!&ndash;   end of slider area&ndash;&gt;-->
<!--    <section class="footer-area" id="contact">-->
<!--        <div class="container">-->
<!--            <div class="row">-->
<!--                <div class="col-md-4 col-sm-3 col-xs-12 col-lg-4">-->
<!--                    <div class="single-footer">-->
<!--                        <h2>about us</h2>-->
<!--                        <p>ABOUT US Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-md-2 col-sm-3 col-xs-12 col-lg-2">-->
<!--                    <div class="single-footer">-->
<!--                        <h2>More links</h2>-->
<!--                        <ul class="list">-->
<!--                            <li><a href="#">about us.</a></li>-->
<!--                            <li><a href="#">We Accepts.</a></li>-->
<!--                            <li><a href="#">news latters</a></li>-->
<!--                            <li><a href="#">Pricing & plans</a></li>-->
<!--                            <li><a href="#">Calculate</a></li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-md-3 col-sm-3 col-xs-12 col-lg-3">-->
<!--                    <div class="single-footer">-->
<!--                        <h2>We Accepts</h2>-->
<!--                        <a href="#"><img src="img/cards_credt_1.png" alt="#"></a>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col-md-3 col-sm-3 col-xs-12 col-lg-3">-->
<!--                    <div class="single-footer clearfix">-->
<!--                        <h2>news latters</h2>-->
<!--                        <input type="text" class="form-control">-->
<!--                        <input type="submit" class="submt-button" value="submit">-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </section>-->
<!--    &lt;!&ndash;   start copyright text area&ndash;&gt;-->
<!--    <div class="copyright-area">-->
<!--        <div class="container">-->
<!--            <div class="col-xs-12 col-sm-6 col-md-6 text-left">-->
<!--                <div class="footer-text">-->

<!--                </div>-->
<!--            </div>-->
<!--            <div class="col-xs-12  col-sm-6 col-md-6 text-right">-->
<!--                <div class="footer-text">-->
<!--                    <a href="#" class="fa fa-facebook"></a>-->
<!--                    <a href="#" class="fa fa-twitter"></a>-->
<!--                    <a href="#" class="fa fa-linkedin"></a>-->
<!--                    <a href="#" class="fa fa-google-plus"></a>-->
<!--                    <a href="#" class="fa fa-dribbble"></a>-->
<!--                </div>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--    &lt;!&ndash;    end of copyright text area&ndash;&gt;-->

    <!--  jquery.min.js  -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <!--    bootstrap.min.js-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <!--    jquery.sticky.js-->
    <script src="{% static 'js/jquery.sticky.js'%}"></script>
    <!--  owl.carousel.min.js  -->
    <script src="{% static 'js/jquery.meanmenu.js'%}"></script>
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <!--  jquery.mb.YTPlayer.min.js   -->
    <script src="{% static 'js/jquery.mb.YTPlayer.min.js'%}"></script>
    <!--    slick.min.js-->
    <script src="{% static 'js/slick.min.js'%}"></script>
    <!--    jquery.nav.js-->
    <script src="{% static 'js/jquery.nav.js'%}"></script>
    <!--jquery waypoints js-->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <!--    jquery counterup js-->
    <script src="{% static 'js/jquery.counterup.min.js'%}"></script>
    <!--    main.js-->
    <script src="{% static 'js/main.js'%}"></script>
</body>

</html>

e_courier/templates/test.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
<style>
body{
        color: black;
        background: black;

	}
</style>

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Delivery Service</title>

    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css'%}" rel="stylesheet" media="all">
</head>

<form method="post">

    <div class="page-wrapper bg-dark p-t-100 p-b-50">
        <div class="wrapper wrapper--w900">
            <div class="card card-6">
                <div class="card-heading">
                    <h2 class="title">Successfully Login message</h2>
                </div>
                <div class="card-body">
                    <div class="form-row">

                            <div class="name"></div>
                            <div class="value">
                               <h1 >You are now logged in! </h1>
                            </div>
                        </div>


                         <div class="card-footer">



                            <div class="name"></div>
                            <div class="value">
                             <h1>Welcome to our website.. Now you can get service!!</h1>
                            </div>
                </div>
   </div>
            </div>
        </div>
    </div>
</form>

    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>


    <!-- Main JS-->
    <script src="{% static 'js/global.js'%}"></script>
{% endblock %}

e_courier/templates/thanks.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block content %}
<style>
body{
        color: black;
        background: black;

	}
</style>

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colorlib Templates">
    <meta name="author" content="Colorlib">
    <meta name="keywords" content="Colorlib Templates">

    <!-- Title Page-->
    <title>Delivery Service</title>

    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css'%}" rel="stylesheet" media="all">
</head>

<form method="post">

    <div class="page-wrapper bg-dark p-t-100 p-b-50">
        <div class="wrapper wrapper--w900">
            <div class="card card-6">
                <div class="card-heading">
                    <h2 class="title">Successfully Logout message</h2>
                </div>
                <div class="card-body">
                    <div class="form-row">

                            <div class="name"></div>
                            <div class="value">
                               <h1 >You are now logged out!</h1>
                            </div>
                        </div>


                         <div class="card-footer">

                            <div class="name"></div>
                            <div class="value">
                             <h1>Thanks for visiting,  come back soon!!! You should logged in for get service</h1>
                            </div>
                </div>
   </div>
            </div>
        </div>
    </div>
</form>

    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>


    <!-- Main JS-->
    <script src="{% static 'js/global.js'%}"></script>
{% endblock %}